GET http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "value1",
    "password": "value2"
}


POST http://localhost:3000/contacto HTTP/1.1
Content-Type: application/json

{
    "nombre": "value1",
    "email": "value2",
    "descripcion": "value3"
}


###
POST http://localhost:3000/registerCourse HTTP/1.1
Content-Type: application/json

{   
    
    "curso" : "ukelele",
    "nivel":"Intermedio",
    "precio": "50",
    "nombre": "Joaquin",
    "apellido":"Gomez",
    "email":"lolo@gmail.com"
}

###
